import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How strong is the armed forces personnel in the EU?",
  "subtitle": "In 2020, there were 1.913 million armed forces personnel in the EU member states.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,23000,TRUE,In 2006 compulsory military service was reduced to six months.,,,,,,,,\nBelgium,BE,24000,true,Voluntary,,,,,,,,\nBulgaria,BG,37000,true,Voluntary,,,,,,,,\nCroatia,HR,20000,TRUE,Compulsory military service planned for 2026,,,,,,,,,\nCyprus,CY,13000,TRUE,Compulsory military service is 26 months,,,,,,,,,\nCzechia,CZ,27000,FALSE,,,,,,,,,\nDenmark,DK,15000,TRUE,Compulsory military service lasts four to twelve months,,,,,,,,,\nEstonia,EE,7000,TRUE,Compulsory military service lasts eight to eleven months,,,,,,,,,\nFinland,FI,22000,TRUE,Compulsory military service lasts six to twelve months,,,,,,,,,\nFrance,FR,304000,TRUE,Planned voluntary,,,,,,,,\nGermany,DE,183000,TRUE,Planned voluntary,,,,,,,,\nGreece,EL,147000,TRUE,Compulsory military service lasts nine to twelve months,,,,,,,,,\nHungary,HU,46000,FALSE,,,,,,,,,\nIreland,IE,9000,FALSE,,,,,,,,,\nItaly,IT,338000,FALSE,,,,,,,,,\nLatvia,LV,9000,TRUE,Compulsory military service lasts six months,,,,,,,,,\nLithuania,LT,37000,TRUE,Compulsory military service lasts nine months,,,,,,,,,\nLuxembourg,LU,1000,false,Voluntary,,,,,,,,\nMalta,MT,2000,FALSE,,,,,,,,,\nNetherlands,NL,41000,true,Voluntary,,,,,,,,\nPoland,PL,189000,true,Voluntary,,,,,,,,\nPortugal,PT,52000,FALSE,,,,,,,,,\nRomania,RO,128000,TRUE,Planned voluntary,,,,,,,,\nSlovak Republic,SK,18000,FALSE,,,,,,,,,\nSlovenia,SI,7000,FALSE,,,,,,,,,\nSpain,ES,199000,FALSE,,,,,,,,,\nSweden,SE,15000,TRUE,Compulsory military service lasts twelve months,,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 23000,
      "extraInfo": true,
      "text_content": "In 2006 compulsory military service was reduced to six months.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 24000,
      "extraInfo": true,
      "text_content": "Voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 37000,
      "extraInfo": true,
      "text_content": "Voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 20000,
      "extraInfo": true,
      "text_content": "Compulsory military service planned for 2026",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 13000,
      "extraInfo": true,
      "text_content": "Compulsory military service is 26 months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 27000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 15000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts four to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 7000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts eight to eleven months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 22000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts six to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 304000,
      "extraInfo": true,
      "text_content": "Planned voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 183000,
      "extraInfo": true,
      "text_content": "Planned voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 147000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts nine to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 46000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 9000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 338000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 9000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts six months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 37000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts nine months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 1000,
      "extraInfo": false,
      "text_content": "Voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 2000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 41000,
      "extraInfo": true,
      "text_content": "Voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 189000,
      "extraInfo": true,
      "text_content": "Voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 52000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 128000,
      "extraInfo": true,
      "text_content": "Planned voluntary",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovak Republic",
      "id": "SK",
      "value": 18000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 7000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 199000,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 15000,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "fullNumbers",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Worldbank (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Out of the 27 countries in the EU 9 currently have a compulsory conscription. ",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://data.worldbank.org/indicator/MS.MIL.TOTL.P1?locations=EU",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "armed forces personnel",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How strong is the armed forces personnel in the EU?",
    "subtitle": "In 2020, there were 1.913 million armed forces personnel in the EU member states.",
    "textNoteDescription": "Note",
    "textNote": "Out of the 27 countries in the EU 9 have a compulsory conscription. ",
    "textSourceDescription": "Source",
    "textSource": "Worldbank (2026)",
    "linkDataAccessDescription": "Access the data",
    "extraInfo_AT": "In 2006 compulsory military service was reduced to six months.",
    "extraInfo_BE": "Voluntary",
    "extraInfo_BG": "Voluntary",
    "extraInfo_HR": "Compulsory military service planned for 2026",
    "extraInfo_CY": "Compulsory military service is 26 months",
    "extraInfo_DK": "Compulsory military service lasts four to twelve months",
    "extraInfo_EE": "Compulsory military service lasts eight to eleven months",
    "extraInfo_FI": "Compulsory military service lasts six to twelve months",
    "extraInfo_FR": "Planned voluntary",
    "extraInfo_DE": "Planned voluntary",
    "extraInfo_EL": "Compulsory military service lasts nine to twelve months",
    "extraInfo_LV": "Compulsory military service lasts six months",
    "extraInfo_LT": "Compulsory military service lasts nine months",
    "extraInfo_LU": "Voluntary",
    "extraInfo_NL": "Voluntary",
    "extraInfo_PL": "Voluntary",
    "extraInfo_RO": "Planned voluntary",
    "extraInfo_SE": "Compulsory military service lasts twelve months"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "In 2006 compulsory military service was reduced to six months.",
  "extraInfo_HR": "Compulsory military service planned for 2026",
  "extraInfo_CY": "Compulsory military service is 26 months",
  "extraInfo_DK": "Compulsory military service lasts four to twelve months",
  "extraInfo_EE": "Compulsory military service lasts eight to eleven months",
  "extraInfo_FI": "Compulsory military service lasts six to twelve months",
  "extraInfo_EL": "Compulsory military service lasts nine to twelve months",
  "extraInfo_LV": "Compulsory military service lasts six months",
  "extraInfo_LT": "Compulsory military service lasts nine months",
  "extraInfo_SE": "Compulsory military service lasts twelve months"
});